version: '3.8'

networks:
  ds-net:
    driver: bridge

services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=sampledb
    volumes:
      - mongo_data:/data/db
    networks:
      - ds-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"  # management UI only
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ds-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URL:   mongodb://mongodb:27017/sampledb
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - ds-net

  worker:
    build: ./worker
    container_name: worker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - ds-net

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - ds-net

volumes:
  mongo_data:
  rabbitmq_data:
